### ISSUE TITLE
Slim\App::setBasePath method missing

### ISSUE THREAD

**Issue by piotr-cz** [selective-php/basepath#1]
Slim [App v4](https://github.com/slimphp/Slim/blob/4.2.0/Slim/App.php) doesn't have `setBasePath` method.

Also
```php
$app->getRouteCollector()->setBasePath($basePath);
```
doesn't work, but this is Slim issue

**Comment by odan** [comment]
Not true. The [App](https://github.com/slimphp/Slim/blob/4.2.0/Slim/App.php#L30) class extends [RouteCollectorProxy](https://github.com/slimphp/Slim/blob/378abc6f8fe43dc7a73537259da728cb27a64332/Slim/Routing/RouteCollectorProxy.php).

The RouteCollectorProxy class has a method: [setBasePath](https://github.com/slimphp/Slim/blob/378abc6f8fe43dc7a73537259da728cb27a64332/Slim/Routing/RouteCollectorProxy.php#L112).

![image](https://user-images.githubusercontent.com/781074/63939903-a0852280-ca68-11e9-9313-ff5964993f2d.png)


> doesn't work, but this is Slim issue

I think it's not a Slim (4) issue, it's just a setup issue.

**Comment by piotr-cz** [comment]
Sorry, you are right.
But still `RouteCollectorProxy::getBasePath` method is never called to route request after base path is set in my case

**Comment by odan** [comment]
> RouteCollectorProxy::getBasePath method is never called 

This is true, because Slim 4 uses `$this->basePath` directly, without calling `getBasePath`. But this is a Slim issue.
