### ISSUE TITLE
Incorrect base path on Firefox

### ISSUE THREAD

**Issue by samuelgfeller** [selective-php/basepath#13]
Hi,
When accessing the link `http://localhost/slim-example-project` on Firefox I get a 404 Not Found, whereas on Chromium it works nicely.

I looked into the source code and here is the difference I've found:
### Chrome
`$server['SCRIPT_NAME']` equals `/slim-example-project/public/index.php`.

![chrome](https://i.imgur.com/ZvLodOe.png)
### Firefox
`$server['SCRIPT_NAME']` equals `/public/index.php`.

![firefox](https://i.imgur.com/b5HNTkk.png)

Is there something wrong with my htaccess? I can't access any local htdocs project on firefox. I get the 404 Not Found even on `localhost/test` and it stops on the breakpoint I set in the project `slim-example-project`. How is this even possible? When I'm trying to access another project, the `$server['SCRIPT_NAME']` of  `slim-example-project/.../BasePathDetector.php` equals to `/public/index.php` as well.

**Comment by odan** [comment]
This is technically not possible because the `$server['SCRIPT_NAME']` is a server variable that is not affected by the browser.
Do you use the same URL in both browsers?
Can you try the same with Postman?

> Is there something wrong with my htaccess?

Paste your .htaccess to have a look at it.

**Comment by samuelgfeller** [comment]
In the following tests, I tried to access the main page firstly normally with the different browsers. 
Below each "normal request" screenshot, I added also a test result of a run with the following exception inserted in `BasePathDetector.php` on line 80.
```php
$scriptName = $server['SCRIPT_NAME'];
throw new \RuntimeException('$server[\'SCRIPT_NAME\'] : '. '"' . $server['SCRIPT_NAME'] . '"');
```

## Accessing slim project 
`http://localhost/slim-example-project`
### Postman (working as expected)
![Postman](https://i.imgur.com/x32EseS.png)
And when I throw exception with `$server['SCRIPT_NAME']` [we can observe](https://i.imgur.com/3q0eoE3.png) that the script name value is `/slim-example-project/public/index.php`

### Edge
![Edge](https://i.imgur.com/oGQ9QC4.png)
Note: I did make the request without the trailing slash, but after page load it added it.   

And when I throw exception of the script name value we can see that here too that `$server['SCRIPT_NAME']` is `/slim-example-project/public/index.php` (correct).

![value of script name](https://i.imgur.com/DoCWFcH.png)


### Firefox
![Firefox without slash](https://i.imgur.com/kQEom4G.png)
And [here](https://i.imgur.com/m2NN1cb.png) with trailing slash

When I load the link on Firefox with the script name in the exception message, we can see that it's only `/public/index.php`
![script name firefox](https://i.imgur.com/J3ceyMx.png)

And [here](https://i.imgur.com/moDBRBO.png) with trailing slash

### Insomnia (same as Firefox)
![Result screenshot](https://i.imgur.com/jUsybVl.png)

[Result insomnia with script name in exception message](https://i.imgur.com/uNKdQ40.png)

## Accessing another project
I made a test file `htdocs/test/test.php` that only contains `<?php echo $_SERVER['SCRIPT_NAME'];` and made the requests with the added exception with server script name in `slim-example-project/.../BasePathDetector.php` right below line 79. 

### Postman (working as expected)
![postman](https://i.imgur.com/QGP3Odh.png)

### [Insomnia](https://insomnia.rest/) (same result as with firefox)
![Insomnia](https://i.imgur.com/6Gfp12d.png)

### Edge
![edge](https://i.imgur.com/8G3g0oc.png)

### Chrome 
![chrome](https://i.imgur.com/MRKxwUX.png)

### Firefox
![firefox](https://i.imgur.com/0tmBFh3.png)    
And [here](https://i.imgur.com/QDBXsvh.png) is the original exception, when the `BasePathDetector.php` is unchanged. 


> Paste your .htaccess to have a look at it.

Of course, I forgot.  
Here is the `htdocs/slim-example-project/.htaccess`
```
RewriteEngine on
RewriteRule ^$ public/ [L]
RewriteRule (.*) public/$1 [L]
```
`slim-example-project/public/.htaccess`
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

**Comment by odan** [comment]
You need a index.php file in your public/ directory. It will not work with a filename like `test.php`.

**Comment by samuelgfeller** [comment]
There are kind of 2 issues going on at the same time. I initially wrote about not being able to access `localhost/slim-example-project` on Firefox and then in my reply wrote the details and tests on the other related issue that I have which is that I cannot open the other projects (in my htdocs folder) files in a browser hence the tests with `localhost/test/test.php`.   
`localhost/{any-project}` routes to the `htdocs/slim-example-project/public/index.php` on Firefox and Insomnia, but not Chrome and Postman. 

Genuine apologies for being so unclear, I think between before Easter, and today I forgot what I wrote in the issue and when testing the problem today I was stuck with not being able to open other projects on Firefox and then wrote about that.

Tomorrow I will make an edit of my answer above to clarify a lot of things and add more testing, alongside with more details on the other related issue.

**Comment by samuelgfeller** [comment]
I now edited [this](https://github.com/selective-php/basepath/issues/13#issuecomment-1101387294) comment with more test results.

**Comment by odan** [comment]
Make sure that `mod_rewrite` is enabled in Apache.
Then post the result using the Slim Server Configuration Checker: https://github.com/odan/slim-checker
If possible, post a link to a (repo) with minimal example.

**Comment by samuelgfeller** [comment]
I put the check directly in `htdocs` and tested (results here probably not so relevant)
![chromium](https://i.imgur.com/Re0OyAt.png)

**On Firefox:**
![Firefox](https://i.imgur.com/ys9vKhp.png) 

No matter, where I put `check.php` I can't access it via Firefox because the Apache or whatever routes it to the slim-example-project index.php. 
There is probably something wrong somewhere in the configuration, and it doesn't help that it only happens on Firefox and insomnia...

**Comment by odan** [comment]
Now try to put this file into your project `public/` directory and try to open it. What is the result?
If this does not work, then something is wrong with the Apache configuration.

**Comment by samuelgfeller** [comment]
Okay, I put it in the public directory:
* `http://localhost/slim-example-project/check.php` in Edge: [screenshot](https://i.imgur.com/L8P1Ubm.png)
* `http://localhost/check.php` in Edge: [screenshot](https://i.imgur.com/dOo4CUz.png)
* `http://localhost/check.php` in Firefox: [screenshot](https://i.imgur.com/uu0Y928.png) 
* `http://localhost/slim-example-project/check.php` in Firefox: [screenshot](https://i.imgur.com/kKTPTcd.png)

It seems that for Firefox, `localhost` means `htdocs/slim-example-project/` instead of just `htdocs`. I thought it may be related to the windows `hosts` file, where I [commented out](https://i.imgur.com/STVegIc.png) that `127.0.0.1` goes to `dev.slim-example-project` and also renamed `httpd-vhosts.conf` to something else.

**Comment by samuelgfeller** [comment]
> If this does not work, then something is wrong with the Apache configuration.

Yes most probably, but where could be the error when I removed httpd-vhosts and why only on Firefox? I also don't understand why sometimes the xdebug debugger works in some projects but other not. Apache is still a bit of a black box for me.

**Comment by odan** [comment]
The Edge screenshots looks perfect, but the Firefox screenshot makes no sense. 
The extra DNS records are not needed, localhost should work just fine.
Try to clear the Firefox browser cache, clear the DNS cache with `ipconfig /flushdns` and restart the webserver.

**Comment by samuelgfeller** [comment]
> The extra DNS records are not needed, localhost should work just fine.

Yes they are old ones, since I use slim and your `basePathMiddleware` I only use `localhost/xproject`.

> The Edge screenshots looks perfect, but the Firefox screenshot makes no sense.

Curiously, I get the [exact same results](https://i.imgur.com/r3ScC5a.png) with insomnia, where you can do requests like postman. Postman, on the other hand, has the [same results](https://i.imgur.com/JOVfuxu.png) as Edge and Chrome.

[Here](https://i.imgur.com/R7K5xVE.png) it is clear that `localhost` points to the slim example project (with Insomnia the same)

> Try to clear the Firefox browser cache, clear the DNS cache with ipconfig /flushdns and restart the webserver.

Restarting the webserver made the difference! I replaced `httpd-vhosts.conf` with a blank file and suddenly everything works as expected 🥳

![yes](https://i.imgur.com/SNGLzr7.png)

There must have been something critically wrong with how I declared the paths in the virtualhosts file: 
```conf
## SLIM EXAMPLE PROJECT ##
<VirtualHost dev.slim-example-project:80>
    DocumentRoot "C:/xampp/htdocs/slim-example-project"
    ServerName dev.slim-example-project
	DirectoryIndex index.php
	<Directory "C:/xampp/htdocs/slim-example-project">
		AllowOverride All
		Allow from All
	</Directory>
</VirtualHost>

## TIME SHEET ##
<VirtualHost dev.time-sheet-api:80>
    DocumentRoot "C:/xampp/htdocs/time-sheet-api"
    ServerName dev.time-sheet-api
	DirectoryIndex index.php
	<Directory "C:/xampp/htdocs/time-sheet-api">
		AllowOverride All
		Allow from All
	</Directory>
</VirtualHost>
``` 

Thanks for your help, have a good night!
