### ISSUE TITLE
Different api.domain.com and domain.com on 1 install?

### ISSUE THREAD

**Issue by inpresif** [selective-php/basepath#14]
Hi,

First off: sorry if this is not the right space for the question, but it's been posted to StackExchange as well with zero replies in a ~week.

I'd love to know if it is possible to run our api calls from a subdomain while keeping the frontend in the root. We use basepath as suggested here, but having a little trouble getting the sub-domain going.

I tried 
```
RewriteEngine On

# Redirect api.xyz.ai/api/* to api.xyz.ai/*
RewriteCond %{HTTP_HOST} ^api.xyz.ai$ [NC]
RewriteRule ^api/(.*)$ https://api.xyz.ai/$1 [R=301,L]

# Rewrite requests to /api/* to the subdomain
RewriteCond %{HTTP_HOST} ^api.xyz.ai$ [NC]
RewriteRule ^api/(.*)$ /public/api/$1 [L]

RewriteRule ^$ public/ [L] 
RewriteRule (.*) public/$1 [L]

```
The subdomain is set to point to the same root as the domain itself.

Thanks.

**Comment by odan** [comment]
Yes, it is possible to run API calls from a subdomain while keeping the frontend in the "root". Make sure that the subdomain is properly set up and pointing to the correct documentRoot directory. You can verify this by creating a test file in the subdomain's root directory and accessing it directly via the subdomain's URL. Ensure that your API calls are using the correct URL. Check your server logs for any errors or issues related to the rewrite rules.

When running API calls from a subdomain, you may encounter CORS (Cross-Origin Resource Sharing) issues. CORS is a security feature that prevents scripts from making requests to a different domain than the one that served the script.

To resolve CORS issues, you need to configure your server to allow cross-origin requests from your subdomain. This can typically be done by adding appropriate headers to your API responses.

In addition to configuring the server, you may also need to update your API client code to include the appropriate CORS headers in the requests.

If you're still experiencing issues, it might be helpful to provide more details about the specific problem you're encountering.

**Comment by inpresif** [comment]
Thanks Daniel. 

It's no problem running the subdomain along the main domain install, but the devil is in the detail.

Here's what is *not* working (yet).
Insead of 
`domain.com/api/anything
`
I want it to go to 
`api.domain.com/anything
`
and not
`api.domain.com/api/anything
`

And here's the route for the API:
```
    $app->group('/api', function (RouteCollectorProxy $group) {
        $group->get('/anything', [\App\Controllers\Api\v1\ApiController::class, 'apihome']);
    })->add(ApiAuthorizationMiddleware::class);
```

Does that make sense?

**Comment by odan** [comment]
I'm not sure if all these makes sense. The server is on the same host, so why all this stress for nothing?

**Comment by inpresif** [comment]
There is no stress ;).

Yes it is on the same host but as per my example, what I want does not seem to work (for me).

**Comment by odan** [comment]
My question is, if your frontend and backend are on the same host/server, why do you need a different domain?

**Comment by inpresif** [comment]
I always use api.domain.com on all our REST projects. The regular URL is for the front-end and I like to keep the URL for API calls separated. It may help if things scale and we need to seperate the two. That way our users do not have to make any changes on their end.

If not a functional reason at this point, it is a cosmetic one. If impossible I will use something like (the less favored) api.domain.com/v1/home

**Comment by odan** [comment]
I think when your users get to the point where they suddenly need to scale, they need more than just changing the URL, because the application itself needs to be prepared for such a complex (and theoretical) use case. You need a different architecture and process that allows you to run and deploy the frontend and the backend separately. So there is a lot more to consider in order to prepare your application for scaling. Try not to solve imaginary scaling issues ;-)

**Comment by vlad-vk** [comment]
Hello. It is necessary to make the links work too.

`$app->get('/', function (Request $request, Response $response) {
    $response->getBody()->write('LINK: <a href="/hello/world">/hello/world</a>');
    return $response;
});
$app->get('/hello/{name}', function (Request $request, Response $response, $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});
`

**Comment by vlad-vk** [comment]
Hello. It is necessary to make the links work too.

$app->get('/', function (Request $request, Response $response) {
    $response->getBody()->write('LINK: <a href="/hello/world">/hello/world</a>');
    return $response;
});
$app->get('/hello/{name}', function (Request $request, Response $response, $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});

**Comment by vlad-vk** [comment]
Hello. It is necessary that the links also work from Apache.

$app->get('/', function (Request $request, Response $response) {
    $response->getBody()->write('LINK: <a href="/hello/world">/hello/world</a>');
    return $response;
});
$app->get('/hello/{name}', function (Request $request, Response $response, $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});
