### ISSUE TITLE
BasePathDetector::getBasePathFromApache returns wrong path

### ISSUE THREAD

**Issue by newHagen** [selective-php/basepath#5]
Hi,

I had an issue finding the correct base path for my Slim 4 App with this tool.
The method getBasePathFromApache might fall one directory short of reality.

In a case, where the index.php to setup the app is called two or more directories below the webroot, a base path is returned, where the last directory is missing.

Example:
Calling the app like this: http://localhost/projects/exampleapp/api/
The intended result is "/projects/exampleapp/api", which might end up as "https://example.com/api" in production.
But it returns: "/projects/exampleapp". 
This is caused by the duplicate use of "dirname()" on the scriptname in line 86 of the file BasePathDetector.php.

After reducing the line to a single call of "dirname()" the result is correct. At least in my use case.

What is the intention of calling dirname twice?
Which sideeffects would it cause to ommit one call?

Best regards,

Hagen

**Comment by odan** [comment]
The first namename removes the script filename: `index.php` and the second call removes the `public/` directory from to get the basepath.

```php
<?php

$serverScriptName = '/slim4-skeleton/public/index.php';

$scriptName = str_replace('\\', '/', dirname(dirname($serverScriptName)));

echo $scriptName; // Output: /slim4-skeleton
```
https://3v4l.org/KHWRD

**Comment by odan** [comment]
Any feedback?
